apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zywx9e76y-nodejs
  janus-idp.io/tekton: zywx9e76y-nodejs
  backstage.io/kubernetes-id: zywx9e76y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zywx9e76y-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
