apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zywx9e76y-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zywx9e76y-nodejs 
  name: zywx9e76y-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zywx9e76y-nodejs 
