apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zywx9e76y-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:3d865e2c7941f3de8cfb5880a541c8fbbeaae8fb@sha256:b307782dd705adb1069f1029ec4e304fab807ecfc563575e34ec9b6901cbf40b
          name: container-image
